global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:5001']

  - job_name: 'recipe_service'
    static_configs:
      - targets: ['recipe_service:5002']
